# Generated by Django 6.0.4 on 2026-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
